export const BASE_URL = "http://localhost:3000"
export const AUTH_URL = "/api/auth"
export const COURSE_URL = "/api/courses"
export const SECTION_URL = "/api/sections"
export const PROGRESS_URL = "/api/progress"
